### ISSUE TITLE
iotune can be wrong on EBS drive

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#1030]
In scylla issue #9906 there's such an io-properties.yaml file 
```
disks:
  - mountpoint: /var/lib/scylla
    read_iops: 32004
    read_bandwidth: 262607760
    write_iops: 34608
    write_bandwidth: 265524816
```
however, the drive was created with default bandwidth, which is 128MB/s. This number also shows up if re-running iotune by hands
