### ISSUE TITLE
Rounding kills min io latency goal estimation

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#1135]
With the io-properties file
```
disks:
  - mountpoint: /home/xfs
    read_iops: 753
    read_bandwidth: 522762976
    write_iops: 4402
    write_bandwidth: 505988832
```

the `_capacity_rate` is calculated from `48192:65345372` by scaling it 1k times and gets `48:65345`. The minimal IO ticket being `128:128` results in `2.6686255931854248` capacity while the capacity limit is `2.6560424966799467`, 0.5% off in the wrong direction :(
