### ISSUE TITLE
Cross-shard preemption is needed

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#1430]
As seen in, e.g. scylladb/scylla#12562, high-prio class with low-concurrency workload is in trouble.

- all shards have all low-prio queues full, disk is fully dispatched, shards line-up on shared token bucket
- high-prio request pops up on some shard
- scheduler decides that the new class should preempt everything, but the best it can do is preempt everything _on_ _this_ _shard_ _only_

As a result, the high-prio request happens in the middle of the global token queue and have chances to get dispatched only after all the preceding other shards complete their IO

Can be reproduced with io_tester:
`io_tester --conf jobs.yaml --storage /dev/null  --duration 5`
and jobs.yaml being
```
- name: big_writes
  shards: all
  type: seqwrite
  data_size: 1GB
  shard_info:
    rps: 8000
    parallelism: 2
    reqsize: 128kB
    shares: 80

- name: latency_reads
  shards: all
  type: randread
  data_size: 1GB
  shard_info:
    rps: 250
    parallelism: 1
    reqsize: 512
    shares: 1000
  options:
    pause_distribution: poisson
```
