### ISSUE TITLE
Assertion `pc._plugged && pc._queued' failed

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#1899]
There's a bug in unplugging IO priority class in duplex mode

```c++
void fair_queue::unplug_priority_class(priority_class_data& pc) noexcept {
    assert(pc._plugged);
    if (pc._queued) {
        pop_priority_class(pc);
    }
    pc._plugged = false;
}
```

the thing is that `pop_...` thing only works on the class that is on top of the handles queue. Usually this constraint is satisfied, because unplug happens from throttle, which in turn happens when dispatching a requests and dispatch happens from top class only. However, in duplex mode throttling tries to unplug classes from two streams, and the "other" one may happen not to be on top of its handles

**Comment by xemul** [comment]
Conf file for reproducing with io-tester (io-properties must exist too with duplex=true)

```
- name: a
  shards: all
  type: seqwrite
  data_size: 1GB
  shard_info:
    parallelism: 1
    reqsize: 256kB
    shares: 10
    bandwidth: 10MB

- name: b
  shards: all
  type: randread
  data_size: 1GB
  shard_info:
    parallelism: 1
    reqsize: 4kB
    shares: 100
    bandwidth: 10MB

- name: c
  shards: all
  type: randread
  data_size: 1GB
  shard_info:
    parallelism: 1
    reqsize: 4kB
    class: a

- name: d
  shards: all
  type: seqwrite
  data_size: 1GB
  shard_info:
    parallelism: 1
    reqsize: 128kB
    class: b
    bandwidth: 10MB
```
