### ISSUE TITLE
IO Scheduler report costs 0 if read_iops,read_bandwidth get big values

### ISSUE THREAD

**Issue by robertbindar** [scylladb/seastar#2816]
Running `ioinfo` with the io-properties-file below will have IO scheduler report a cost of 0 for reads. The default numbers for when the scheduler runs unconfigured are UINT64_MAX.

```yaml
disks: 
  - mountpoint: /var/lib/scylla/somedir
    read_iops: 3355443200000
    read_bandwidth: 33554432G
    write_iops: 1000
    write_bandwidth: 1000M
```

Refs: https://github.com/scylladb/seastar/issues/2802
