### ISSUE TITLE
ioinfo hangs if the write requests are configured with big numbers in io-properties-file

### ISSUE THREAD

**Issue by robertbindar** [scylladb/seastar#2817]
Running ioinfo with
```yaml
disks: 
  - mountpoint: /var/lib/scylla/robitza
    read_iops: 1000
    read_bandwidth: 1000M
    write_iops: 25600000
    write_bandwidth: 256G
```
makes the tool hang.
My gdb seems to wander around this [function](https://github.com/scylladb/seastar/blob/master/src/core/io_queue.cc#L645) 

Refs: https://github.com/scylladb/seastar/issues/2802
