### ISSUE TITLE
Unconfigured io-properties render some too large costs

### ISSUE THREAD

**Issue by robertbindar** [scylladb/seastar#2819]
The IO scheduler outputs large costs for read/write requests when running without io-properties, this is what an `ioinfo` run
shows on a i7i.12xlarge machine:
```
disk_read_max_length: 4194304
disk_write_max_length: 4194304
device: 2304
io_latency_goal_ms: 0.75
io_queue:
  id: 0
  req_count_rate: 2147483647
  blocks_count_rate: 2147483647
  disk_req_write_to_read_multiplier: 128
  disk_blocks_write_to_read_multiplier: 128
fair_queue:
  capacities:
    512:
      read: 2000
      write: 2000
    1024:
      read: 3000
      write: 3000
    2048:
      read: 5000
      write: 5000
    4096:
      read: 9000
      write: 9000
    8192:
      read: 17000
      write: 17000
    16384:
      read: 33000
      write: 33000
    32768:
      read: 65000
      write: 65000
    65536:
      read: 129000
      write: 129000
    131072:
      read: 257000
      write: 257000
  per_tick_grab_threshold: 262144
  token_bucket:
    limit: 12582912
    rate: 16777216
    threshold: 2000
```
If you take the 128k request, the computed bandwidth is ~8.1GB/s which is very similar to the throttling point we hit in #2802 

Refs: https://github.com/scylladb/seastar/issues/2802
