### ISSUE TITLE
HDD disks are underutilized with default config

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#584]
Introduced in 97cc0de6ea38b6787fbb897c16cc5242cd4762fc.

IO concurrency allowed to the disk is now calculated as `max(read_iops, write_iops) * latency_goal`, where `latency_goal` is `task_quota * 1.5` = `0.75 ms`. This assumes that latency of the disk is lower. If it's not, the allowed concurrency to the disk will be too low to reach full throughput. For HDDs the latency can be around `7ms`.

It can be worked around by manually scaling `read_iops`, `read_bandwidth`, `write_iops` and `write_bandwidth` in `io_properties.yaml`.

**Comment by slivne** [comment]
Can we detect this automatically (https://unix.stackexchange.com/questions/65595/how-to-know-if-a-disk-is-an-ssd-or-an-hdd)  and not have the user to input this information.

By default it would be better if we detect this automatically and not have the user to specify.

**Comment by avikivity** [comment]
We don't need to care about whether the disk is an HDD or SSD, we just need to measure its latency. So far we've only been measuring throughput.

We'll see the same problem with network-attached storage with latency > 0.5ms (like cloud network disks).

**Comment by joachimdraeger** [comment]
I hit this problem when testing write throughput on an AWS EC2 im4gn.large instance with `ami-02dc1847c8c7d24a2`,  ScyllaDB 5.4.0.

The values that have been automatically added to `io_properties.yaml`  made sense for the instance type:
```yaml
disks:
- mountpoint: /var/lib/scylla
  read_bandwidth: 288433525
  read_iops: 33943
  write_bandwidth: 126864680
  write_iops: 27877
```
However, I was only getting about 80 MB/s when trying to max out throughput. I only found this issue after suspecting that some of the tuning might not be correct.
I got much better results with applying a factor of 1.6 to all values, ultimately maxing out write speed with factor 4:

```yaml
disks:
- mountpoint: /var/lib/scylla
  read_bandwidth: 1152000000
  read_iops: 136000
  write_bandwidth: 508000000
  write_iops: 112000
```
