### ISSUE TITLE
Revise reactor polling overhead

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#987]
If running the rate-limited IO workload, acheiving high requests-per-second rate is impossible if sleeping between submissions -- reactor consumes more time that it should pass between submissions. Increasing the number of fibers also doesn't help. The work-able solution is to use `options.polling_sleep` feature to make workload busy-loop between submissions.

Reproduceable with io_tester script

```
- data_size: 8192MB
  name: read_rated_100000
  shard_info:
    parallelism: 16
    reqsize: 1kB
    rps: 251
    shares: 100000
  shards: all
  type: randread
```

The `parallelism * rps` should remain constant.
