### ISSUE TITLE
Sched-group shares vs IO-class shares

### ISSUE THREAD

**Issue by xemul** [scylladb/seastar#988]
Right now scylla (and io-tester too) configure different "workloads" with equal shares set on both -- sched group and IO class. This, however, sometimes results in a hard-to-predict interaction. In particular, two different IO workloads are naturally expected to share disk capacity according to their shares, however CPU scheduler doesn't always let read and write fibers to be run at the desired rate.

Came from the io-tester script:

```
- data_size: 8192MB
  name: read_rated
  shard_info:
    parallelism: 16
    reqsize: 4kB
    rps: 251
    shares: 2500
  shards: all
  type: randread
- data_size: 8192MB
  name: write_unbound
  shard_info:
    parallelism: 2
    reqsize: 64kB
    shares: 100
  shards: all
  type: seqwrite
```

It turns out to be very sensitive to the number of reading fibers.
